"""empty message

Revision ID: 582cdb88479f
Revises: 
Create Date: 2022-08-24 17:57:26.623278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '582cdb88479f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():

    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: This was generated from the models.py file. After updated models.py, we used:
    # cd flask/twitter
    # flask db migrate
# The second command generated this file:
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###

# Making this file doesn't apply the changes. To apply the changes, run the following code from the /week3/flask/twitter folder:
# flask db upgrade

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
